"""empty message

Revision ID: 030d83c08c64
Revises: 8c5c505e2e51
Create Date: 2025-02-05 20:38:22.041032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030d83c08c64'
down_revision = '8c5c505e2e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cpf'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
