"""adiciona name to procedure

Revision ID: 8a07e51c89e5
Revises: d21a434b67c9
Create Date: 2025-04-01 16:18:43.149075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a07e51c89e5'
down_revision = 'd21a434b67c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
